export const Config = {
  GRAPHQL_ENDPOINT: import.meta.env.VITE_APP_GRAPHQL_ENDPOINT,
  MY_TELEGRAM_ID: import.meta.env.VITE_APP_MY_TELEGRAM_ID,
  SUPPORTED_LANGUAGES: import.meta.env.VITE_APP_SUPPORTED_LANGUAGES,
  I18N_LOCALE: import.meta.env.VITE_APP_I18N_LOCALE,
  I18N_FALLBACK_LOCALE: import.meta.env.VITE_APP_I18N_FALLBACK_LOCALE
}
